POST http://localhost:8000/v1/models/create  HTTP/1.1
content-type: application/json

{
    "model_name":"test",
    "algorithm": "egreedy",
    "epsilon": 0.1,
    "actions": ["left", "right"],
    "n_actions": 2
}